### PR TITLE
Add recommendation for string-indexed objects

### PR DESCRIPTION
**Pull request by sindresorhus**

### CODE REVIEW

**Comment by sindresorhus** [comment]
// @BendingBender

**Comment by felixfbecker** [comment]
There’s a huge problem with using ~~`{[key: string]: any}`~~ `{[key: string]: number}` for parameters over object. It says “the object passed must have an index signature”, which means if you have any plain object that is typed as any interface, it will not be possible to pass that object as it doesn’t have the index signature.

There is simply no way right now to declare “any object, where all properties have this type”. It also is fundamentally impossible with structural typing and polymorphism, because you may pass a supertype that has more non-compliant properties that TypeScript doesn’t know about. It would need exact types in the language first.

**Comment by BendingBender** [comment]
@sindresorhus `permissable` -> `permissive`
@felixfbecker Not sure what you mean here. Can you provide an example that doesn't work as expected with `{[key: string]: any}`?

**Comment by felixfbecker** [comment]
It's a problem with the `{ [key: string]: number }` type recommended in the guideline: [Playground link](https://www.typescriptlang.org/play/index.html?target=6#code/JYOwLgpgTgZghgYwgAgFIGcD2JkG8BQyRyA2gNYQCeAXMumFKAOYC6tIArgLYBG0+AX3z4YHEAjDBsyGJkwAKAFZYQtDNgCUtAG6ZgAEzzCh+UJFiIUAeR6KjxZAAcomR+258og4Qmz1kmLa0NnYAvPbEzq60AIwATADM3iJy8oGKGvhAA)

This is a very common pitfall. `{ [key: string]: any }` behaves in a special way, but it is impossible to e.g. define a type for serializable values (for `JSON.stringify()`, `postMessage()`, etc) like

```ts
interface JsonObject {
  [key: string]: number | string | boolean | JsonObject
}
```

Many devs _think_ this does what they want because it works when you just pass an object literal, but then when you have an object that is typed as an interface that _should_ pass it fails. Therefor I would advise to educate about this pitfall so people don't end up using it in public interfaces.

**Comment by BendingBender** [comment]
Good point. It's usually not a problem because people tend to use object literals all over the place but you're right, that's a real problem.

**Comment by sindresorhus** [comment]
@felixfbecker I'm not exactly sure what you want changed in the guide, but PR welcome to clarify things.

**Pull request merged**
